name: wanki_env
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pip  
  - dash
  - dash-bootstrap-components
  - pandas
  - plotly
  - python
  - scipy
  - pip:
    - https://github.com/PEM-Humboldt/wiutils/tarball/master
